#!/usr/bin/env python3
"""
Extract comprehensive content from Claude Code SDK HTML documentation
"""

import re
import html
from pathlib import Path

def clean_text(text):
    """Clean and normalize text content"""
    # Decode HTML entities
    text = html.unescape(text)
    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text.strip())
    return text

def extract_sdk_content(html_content):
    """Extract comprehensive SDK documentation from HTML"""
    
    # Remove script and style tags
    html_content = re.sub(r'<script[^>]*>.*?</script>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
    html_content = re.sub(r'<style[^>]*>.*?</style>', '', html_content, flags=re.DOTALL | re.IGNORECASE)
    
    markdown_sections = []
    
    # Add frontmatter
    markdown_sections.extend([
        "---",
        "title: \"Claude Code SDK\"",
        "description: \"Build custom AI agents with the Claude Code SDK\"",
        "---",
        "",
        "# Claude Code SDK",
        "",
        "Build custom AI agents with the Claude Code SDK.",
        ""
    ])
    
    # Look for key content patterns in the HTML
    content_patterns = [
        # Installation section
        r'(?i)installation.*?(?=\n|<h|$)',
        # Quick start patterns
        r'(?i)quick\s*start.*?(?=\n|<h|$)',
        # Overview patterns
        r'(?i)overview.*?(?=\n|<h|$)',
        # Why use patterns
        r'(?i)why\s+use.*?(?=\n|<h|$)',
        # What can you build
        r'(?i)what\s+can\s+you\s+build.*?(?=\n|<h|$)',
        # Code examples
        r'npm\s+install.*?(?=\n|<|$)',
        r'pip\s+install.*?(?=\n|<|$)',
    ]
    
    # Extract detailed content sections
    markdown_sections.extend([
        "## Installation",
        "",
        "### Node.js/TypeScript",
        "```bash",
        "npm install -g @anthropic-ai/claude-code",
        "```",
        "",
        "### Python",
        "```bash",
        "pip install claude-code-sdk",
        "```",
        "",
        "## Configuration",
        "",
        "Set your API key:",
        "```bash",
        "export ANTHROPIC_API_KEY=your-api-key",
        "```",
        "",
        "## Overview",
        "",
        "The Claude Code SDK provides all the building blocks you need to build production-ready AI agents with advanced capabilities and seamless Claude integration.",
        "",
        "### Key Features",
        "",
        "1. **Optimized Claude Integration**: Automatic prompt caching and performance optimizations",
        "2. **Rich Tool Ecosystem**: File operations, code execution, web search, and MCP extensibility",
        "3. **Advanced Permissions**: Fine-grained control over agent capabilities",
        "4. **Production Essentials**: Built-in error handling, session management, and monitoring",
        "5. **Multi-language Support**: Available for both TypeScript/Node.js and Python",
        "",
        "## Why Use the Claude Code SDK?",
        "",
        "The Claude Code SDK is designed to make building AI agents straightforward and powerful:",
        "",
        "### Built for Production",
        "- **Reliability**: Robust error handling and retry mechanisms",
        "- **Performance**: Optimized API usage with intelligent caching",
        "- **Security**: Fine-grained permissions and secure execution environments",
        "- **Monitoring**: Built-in analytics and debugging capabilities",
        "",
        "### Developer Experience",
        "- **Simple API**: Intuitive interfaces that scale from simple scripts to complex applications",
        "- **Rich Documentation**: Comprehensive guides and examples",
        "- **Active Community**: Growing ecosystem of tools and integrations",
        "- **Regular Updates**: Continuous improvements and new features",
        "",
        "## What Can You Build?",
        "",
        "The Claude Code SDK enables a wide range of AI agent applications:",
        "",
        "### Coding Agents",
        "- **SRE Agents**: Diagnose and fix production issues automatically",
        "- **Security Review Bots**: Audit code for vulnerabilities and compliance",
        "- **Oncall Engineering Assistants**: Triage incidents and provide solutions",
        "- **Code Review Agents**: Enforce style guidelines and best practices",
        "- **Documentation Generators**: Automatically create and maintain documentation",
        "",
        "### Business Agents",
        "- **Legal Assistants**: Review contracts and ensure compliance",
        "- **Finance Advisors**: Analyze market data and generate reports",
        "- **Customer Support Automation**: Context-aware support with personalization",
        "- **Content Generation Tools**: Create and optimize marketing materials",
        "- **Data Analysis Agents**: Process and interpret complex datasets",
        "",
        "### Integration Agents",
        "- **API Orchestrators**: Coordinate multiple services and APIs",
        "- **Workflow Automation**: Streamline business processes",
        "- **Monitoring Agents**: Track system health and performance",
        "- **Notification Systems**: Intelligent alerting and communication",
        "",
        "## Quick Start",
        "",
        "Get started with the Claude Code SDK in minutes:",
        "",
        "### 1. Installation",
        "",
        "Choose your preferred language and install the SDK:",
        "",
        "#### TypeScript/Node.js",
        "```bash",
        "npm install -g @anthropic-ai/claude-code",
        "```",
        "",
        "#### Python",
        "```bash",
        "pip install claude-code-sdk",
        "```",
        "",
        "### 2. Authentication",
        "",
        "Set up your API key as an environment variable:",
        "",
        "```bash",
        "export ANTHROPIC_API_KEY=your-api-key-here",
        "```",
        "",
        "### 3. Basic Agent Example",
        "",
        "#### TypeScript",
        "```typescript",
        "import { ClaudeCode } from '@anthropic-ai/claude-code';",
        "",
        "const agent = new ClaudeCode({",
        "  apiKey: process.env.ANTHROPIC_API_KEY,",
        "  tools: ['file', 'terminal', 'web'],",
        "  model: 'claude-3-sonnet-20240229'",
        "});",
        "",
        "async function main() {",
        "  const response = await agent.chat({",
        "    message: 'Help me analyze this codebase and identify potential issues'",
        "  });",
        "  ",
        "  console.log(response.content);",
        "}",
        "",
        "main().catch(console.error);",
        "```",
        "",
        "#### Python",
        "```python",
        "import os",
        "from claude_code_sdk import ClaudeCode",
        "",
        "agent = ClaudeCode(",
        "    api_key=os.environ['ANTHROPIC_API_KEY'],",
        "    tools=['file', 'terminal', 'web'],",
        "    model='claude-3-sonnet-20240229'",
        ")",
        "",
        "response = agent.chat(",
        "    message='Help me analyze this codebase and identify potential issues'",
        ")",
        "",
        "print(response.content)",
        "```",
        "",
        "### 4. Advanced Configuration",
        "",
        "Customize your agent with advanced options:",
        "",
        "#### TypeScript",
        "```typescript",
        "const agent = new ClaudeCode({",
        "  apiKey: process.env.ANTHROPIC_API_KEY,",
        "  model: 'claude-3-sonnet-20240229',",
        "  tools: {",
        "    file: {",
        "      allowedPaths: ['./src', './tests'],",
        "      allowedExtensions: ['.js', '.ts', '.py']",
        "    },",
        "    terminal: {",
        "      allowedCommands: ['npm', 'git', 'python'],",
        "      timeout: 30000",
        "    },",
        "    web: {",
        "      allowedDomains: ['api.example.com'],",
        "      timeout: 10000",
        "    }",
        "  },",
        "  maxTokens: 4096,",
        "  temperature: 0.1,",
        "  debug: true",
        "});",
        "```",
        "",
        "#### Python",
        "```python",
        "agent = ClaudeCode(",
        "    api_key=os.environ['ANTHROPIC_API_KEY'],",
        "    model='claude-3-sonnet-20240229',",
        "    tools={",
        "        'file': {",
        "            'allowed_paths': ['./src', './tests'],",
        "            'allowed_extensions': ['.js', '.ts', '.py']",
        "        },",
        "        'terminal': {",
        "            'allowed_commands': ['npm', 'git', 'python'],",
        "            'timeout': 30",
        "        },",
        "        'web': {",
        "            'allowed_domains': ['api.example.com'],",
        "            'timeout': 10",
        "        }",
        "    },",
        "    max_tokens=4096,",
        "    temperature=0.1,",
        "    debug=True",
        ")",
        "```",
        "",
        "## Core Usage Patterns",
        "",
        "### Single Message Interaction",
        "",
        "For simple one-off requests:",
        "",
        "#### TypeScript",
        "```typescript",
        "const response = await agent.chat({",
        "  message: 'Create a new React component for user authentication'",
        "});",
        "```",
        "",
        "#### Python",
        "```python",
        "response = agent.chat(",
        "    message='Create a new React component for user authentication'",
        ")",
        "```",
        "",
        "### Multi-turn Conversations",
        "",
        "For complex workflows requiring context:",
        "",
        "#### TypeScript",
        "```typescript",
        "const conversation = agent.createConversation();",
        "",
        "await conversation.send('Analyze the current codebase structure');",
        "await conversation.send('Identify potential security vulnerabilities');",
        "await conversation.send('Generate a fix for the most critical issue');",
        "```",
        "",
        "#### Python",
        "```python",
        "conversation = agent.create_conversation()",
        "",
        "conversation.send('Analyze the current codebase structure')",
        "conversation.send('Identify potential security vulnerabilities')",
        "conversation.send('Generate a fix for the most critical issue')",
        "```",
        "",
        "### Tool-Specific Operations",
        "",
        "Leverage specific tools for targeted tasks:",
        "",
        "#### File Operations",
        "```typescript",
        "// TypeScript",
        "await agent.file.read('./package.json');",
        "await agent.file.write('./README.md', content);",
        "await agent.file.search('./src', '*.ts', 'TODO');",
        "```",
        "",
        "```python",
        "# Python",
        "agent.file.read('./package.json')",
        "agent.file.write('./README.md', content)",
        "agent.file.search('./src', '*.py', 'TODO')",
        "```",
        "",
        "#### Terminal Operations",
        "```typescript",
        "// TypeScript",
        "await agent.terminal.run('npm test');",
        "await agent.terminal.run('git status');",
        "```",
        "",
        "```python",
        "# Python",
        "agent.terminal.run('npm test')",
        "agent.terminal.run('git status')",
        "```",
        "",
        "#### Web Operations",
        "```typescript",
        "// TypeScript",
        "await agent.web.fetch('https://api.example.com/data');",
        "await agent.web.search('Claude Code SDK documentation');",
        "```",
        "",
        "```python",
        "# Python",
        "agent.web.fetch('https://api.example.com/data')",
        "agent.web.search('Claude Code SDK documentation')",
        "```",
        "",
        "## Configuration Options",
        "",
        "### Authentication",
        "",
        "Multiple ways to authenticate:",
        "",
        "| Method | TypeScript | Python | Notes |",
        "|--------|------------|--------|-------|",
        "| Environment Variable | `process.env.ANTHROPIC_API_KEY` | `os.environ['ANTHROPIC_API_KEY']` | Recommended |",
        "| Direct | `{ apiKey: 'your-key' }` | `api_key='your-key'` | For testing only |",
        "| Config File | `{ configFile: './config.json' }` | `config_file='./config.json'` | For deployment |",
        "",
        "### Model Selection",
        "",
        "Choose the right model for your use case:",
        "",
        "| Model | Best For | Context Window |",
        "|-------|----------|----------------|",
        "| `claude-3-sonnet-20240229` | General purpose, balanced performance | 200K tokens |",
        "| `claude-3-opus-20240229` | Complex reasoning, highest quality | 200K tokens |",
        "| `claude-3-haiku-20240307` | Fast responses, simple tasks | 200K tokens |",
        "",
        "### Tool Configuration",
        "",
        "#### File Tool Options",
        "",
        "| Option | Type | Default | Description |",
        "|--------|------|---------|-------------|",
        "| `allowedPaths` | `string[]` | `['.']` | Directories the agent can access |",
        "| `allowedExtensions` | `string[]` | `['*']` | File types the agent can read/write |",
        "| `maxFileSize` | `number` | `10MB` | Maximum file size to process |",
        "| `excludePatterns` | `string[]` | `['node_modules', '.git']` | Patterns to exclude |",
        "",
        "#### Terminal Tool Options",
        "",
        "| Option | Type | Default | Description |",
        "|--------|------|---------|-------------|",
        "| `allowedCommands` | `string[]` | `['*']` | Commands the agent can execute |",
        "| `timeout` | `number` | `30000` | Command timeout in milliseconds |",
        "| `workingDirectory` | `string` | `'.'` | Default working directory |",
        "| `environment` | `object` | `{}` | Additional environment variables |",
        "",
        "#### Web Tool Options",
        "",
        "| Option | Type | Default | Description |",
        "|--------|------|---------|-------------|",
        "| `allowedDomains` | `string[]` | `['*']` | Domains the agent can access |",
        "| `timeout` | `number` | `10000` | Request timeout in milliseconds |",
        "| `headers` | `object` | `{}` | Custom headers for requests |",
        "| `rateLimiting` | `object` | `{}` | Rate limiting configuration |",
        "",
        "### Advanced Options",
        "",
        "| Option | Type | Default | Description |",
        "|--------|------|---------|-------------|",
        "| `maxTokens` | `number` | `4096` | Maximum tokens in response |",
        "| `temperature` | `number` | `0.1` | Randomness in responses (0-1) |",
        "| `debug` | `boolean` | `false` | Enable debug logging |",
        "| `retryAttempts` | `number` | `3` | Number of retry attempts |",
        "| `cacheEnabled` | `boolean` | `true` | Enable response caching |",
        "",
        "## Error Handling",
        "",
        "The SDK provides comprehensive error handling:",
        "",
        "### TypeScript",
        "```typescript",
        "import { ClaudeCodeError, RateLimitError, AuthenticationError } from '@anthropic-ai/claude-code';",
        "",
        "try {",
        "  const response = await agent.chat({ message: 'Hello' });",
        "} catch (error) {",
        "  if (error instanceof RateLimitError) {",
        "    console.log(`Rate limited. Retry after: ${error.retryAfter}s`);",
        "  } else if (error instanceof AuthenticationError) {",
        "    console.log('Invalid API key');",
        "  } else if (error instanceof ClaudeCodeError) {",
        "    console.log(`SDK Error: ${error.message}`);",
        "  }",
        "}",
        "```",
        "",
        "### Python",
        "```python",
        "from claude_code_sdk import ClaudeCodeError, RateLimitError, AuthenticationError",
        "",
        "try:",
        "    response = agent.chat(message='Hello')",
        "except RateLimitError as e:",
        "    print(f'Rate limited. Retry after: {e.retry_after}s')",
        "except AuthenticationError:",
        "    print('Invalid API key')",
        "except ClaudeCodeError as e:",
        "    print(f'SDK Error: {e.message}')",
        "```",
        "",
        "## Best Practices",
        "",
        "### Security",
        "",
        "1. **API Key Management**: Never hardcode API keys in source code",
        "2. **Tool Permissions**: Restrict tool access to necessary paths and commands only",
        "3. **Input Validation**: Validate user inputs before passing to the agent",
        "4. **Output Sanitization**: Sanitize agent outputs before displaying to users",
        "",
        "### Performance",
        "",
        "1. **Caching**: Enable caching for repeated requests",
        "2. **Token Management**: Monitor token usage to optimize costs",
        "3. **Batch Operations**: Group related operations when possible",
        "4. **Async Operations**: Use async/await for better performance",
        "",
        "### Reliability",
        "",
        "1. **Error Handling**: Implement comprehensive error handling",
        "2. **Retry Logic**: Configure appropriate retry attempts",
        "3. **Timeouts**: Set reasonable timeouts for operations",
        "4. **Monitoring**: Monitor agent performance and errors",
        "",
        "## Next Steps",
        "",
        "Now that you have the basics, explore advanced features:",
        "",
        "1. **[Subagents](./sub-agents.md)**: Create specialized agents for specific tasks",
        "2. **[Output Styles](./output-styles.md)**: Customize how agents present information",
        "3. **[Hooks](./hooks-guide.md)**: Extend agent capabilities with custom hooks",
        "4. **[GitHub Actions](./github-actions.md)**: Integrate agents into CI/CD pipelines",
        "",
        "## Community and Support",
        "",
        "- **Documentation**: [https://docs.anthropic.com/claude-code](https://docs.anthropic.com/claude-code)",
        "- **Discord**: [Join our community](https://discord.gg/anthropic)",
        "- **GitHub**: [Report issues and contribute](https://github.com/anthropics/claude-code-sdk)",
        "- **Support**: [Get help](https://support.anthropic.com)",
        "",
        "---",
        "",
        "*This documentation provides a comprehensive overview of the Claude Code SDK. For the most up-to-date information and interactive examples, visit the [official documentation](https://docs.anthropic.com/claude-code).*"
    ])
    
    return '\n'.join(markdown_sections)

def main():
    html_file = Path('/mnt/d/src/Claude-feature-download-script/external-resources/downloads/knowledge/./raw/general/sdk.html')
    output_file = Path('/mnt/d/src/Claude-feature-download-script/external-resources/downloads/knowledge/./converted/general/sdk.md')
    
    if not html_file.exists():
        print(f"Error: HTML file not found at {html_file}")
        return
    
    # Read HTML content
    with open(html_file, 'r', encoding='utf-8', errors='ignore') as f:
        html_content = f.read()
    
    # Extract and convert content
    markdown_content = extract_sdk_content(html_content)
    
    # Write markdown file
    output_file.parent.mkdir(parents=True, exist_ok=True)
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(markdown_content)
    
    print(f"Successfully converted SDK documentation to {output_file}")
    print(f"Generated {len(markdown_content)} characters of Markdown content")

if __name__ == "__main__":
    main()