name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
      - uses: pre-commit/action@v3.0.1
      - uses: DavidAnson/markdownlint-cli2-action@v22
        continue-on-error: true
        with:
          config: "config/claude.markdownlint-cli2.yaml"
      - uses: DavidAnson/markdownlint-cli2-action@v22
        continue-on-error: true
        with:
          config: "config/readme.markdownlint-cli2.yaml"
      - uses: DavidAnson/markdownlint-cli2-action@v22
        continue-on-error: true
        with:
          config: "config/other.markdownlint-cli2.yaml"
